### ISSUE TITLE
commit to semver and release v1

### ISSUE THREAD

**Issue by graingert** [bahmutov/node-hook#11]
I'd like to be able to depend on node-hook@^1.0.0 to make upgrading deps across my whole project easier.

**Comment by bahmutov** [comment]
Version `1.0.0` has been published to NPM. The full release note can be found at [node-hook/releases/tag/v1.0.0](https://github.com/bahmutov/node-hook/releases/tag/v1.0.0).

**Tip:** safely upgrade dependency node-hook in your project using [next-update](https://github.com/bahmutov/next-update)
